# yml template to dockerise a node.js app
version: '3'
services: 
    appservice: 
        container_name: nodeapp
        #build: .
        image: maschroder/image
        ports: 
            - '3001:3000'
        depends_on: 
            - mongoservice
    mongoservice:
        container_name: mongo
        image: mongo 
        ports:
            - '27017:27017'
        volumes:
           # - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
           - ./mongo-volume:/data/db
    mongoexpressservice: 
        image: mongo-express
        restart: always
        ports: 
            - '8081:8081'
        depends_on:
            - mongoservice